### PR TITLE
Fix some code issues

### LINKED ISSUE #1: Code issues found
```rust
use num::clamp;
use regex::Regex;
use std::{process::Command, thread, time};

// Path to control software
const MINIDSP_BINARY: &str = "minidsp";

// Factor to scale gain differences with
const GAIN_SCALE: f64 = 6.0;

// Time to sleep between calls
const SLEEP_TIME_MS: u64 = 50;

// Gain values for miniDSP 2x4 HD
const MINIDSP_GAIN_MIN: f64 = -127.0;
const MINIDSP_GAIN_MAX: f64 = 0.0;

fn get_gain() -> f64 {
    let output = Command::new(MINIDSP_BINARY) // [COMMENT] is this the only way to actually interact with the minidsp? No lib? No API?
        .output()
        .expect("Failed to retrieve current gain");
    let output_string =
        String::from_utf8(output.stdout).expect("Failed to convert output to string");

    // Fetch gain through regex
    let gain_regex =
        Regex::new(r"Gain\((?P<gain>-*\d*\.*\d*)\)").expect("Failed to create regex for gain"); // [COMMENT] won't this regexp actually recompile on each re-run of the method? How about saving the regex compiled once. Regex compilation are not free ;)
    let capture_groups = gain_regex
        .captures(&output_string)
        .expect("Failed to retrieve gain from regex");
    let gain = &capture_groups["gain"] // [COMMENT] Nice that you named the capture group!
        .parse::<f64>()
        .expect("Failed to convert gain to float"); // [COMMENT] Wouldn't optionals make sense? Or you enjoy throwing? ;)
    *gain // [COMMENT] newline before return?
}

fn apply_gain(gain: &str) {
    println!("Setting new gain: {} dB", gain); // [COMMENT] Does it make sense to actually println each time? How about logging to a file instead?
    Command::new(MINIDSP_BINARY)  // [COMMENT] again, no API to call this except through process?
        .arg("gain")
        .arg("--")
        .arg(gain)
        .output()
        .expect("Failed to update gain");
}

fn update_gain(current: f64, new: f64) -> bool {
    let diff = new - current; // [COMMENT] naming. What is the diff about?
    let scaled_gain = current + (diff * GAIN_SCALE);
    let scaled_gain = clamp(scaled_gain, MINIDSP_GAIN_MIN, MINIDSP_GAIN_MAX); // [COMMENT] using the same name? What's the difference? 

    // Stringify to miniDSP format too see if the gain has changed
    let old_gain_string = format!("{:.1}", current);
    let new_gain_string = format!("{:.1}", scaled_gain);

    if old_gain_string != new_gain_string { // [COMMENT] extract this into a variable that's named as you re-use it and also comment that output... 
        // Set new gain // [COMMENT] Why comment apply_gain?
        apply_gain(&new_gain_string); 
    }

    // True = updated gain, false = no update
    old_gain_string != new_gain_string // [COMMENT] I suppose it's standard to return if it worked out? Please name as mentioned.
}

fn main() {
    let mut known = false;
    let mut current_gain = MINIDSP_GAIN_MIN;

    loop {
        let new_gain = get_gain();

        if current_gain != new_gain {
            println!("Current gain: {} dB", new_gain); // [COMMENT] Once again, logging a file perhaps?
        }

        // Only update the gain if we know what the last reference was
        match known { // [COMMENT] Why matcher when it's true/false? If-else would work :) Also, this whole statement is very weird IMO. We first update gain and say... Now we don't know what it is... Then we update to the new_gain... How about we return the gain from `update_gain` instead and then use that to set the `current_gain`?.
            true => known = !update_gain(current_gain, new_gain),
            false => {
                known = true;
                current_gain = new_gain;
            }
        };

        // Sleep until next call
        thread::sleep(time::Duration::from_millis(SLEEP_TIME_MS));
    }
}
```

Ok, read all `// [COMMENT] ` 😄 🔥

### PR DESCRIPTION
**Pull request by ElitCoder**
* Static evaluation for regex to save some CPU cycles
* Variable naming

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -15,23 +16,28 @@ const SLEEP_TIME_MS: u64 = 50;
...
 const MINIDSP_GAIN_MAX: f64 = 0.0;
 
+// Lazy static needed since Regex::new() is a function call
+lazy_static! {
+    static ref GAIN_REGEX: Regex =
+        Regex::new(r"Gain\((?P<gain>-*\d*\.*\d*)\)").expect("Failed to create regex for gain");
+}
+
 fn get_gain() -> f64 {
     let output = Command::new(MINIDSP_BINARY)
```
Comment (ElitCoder) [inline src/main.rs:26]: There seems to be an API that "minidsp" uses, however it would in practice mean re-implementing the whole "minidsp" program... I know that making system calls are horrible, but I don't really see any other solution.

File: src/main.rs [hunk 2]
```diff
@@ -15,23 +16,28 @@ const SLEEP_TIME_MS: u64 = 50;
...
+
+    // Return the gain as a floating number
+    capture_groups["gain"]
         .parse::<f64>()
-        .expect("Failed to convert gain to float");
-    *gain
+        .expect("Failed to convert gain to float")
 }
 
 fn apply_gain(gain: &str) {
```
Comment (ElitCoder) [inline src/main.rs:43]: I think println! is fine here. stdout will be redirected to syslog when using systemd. Not really targeting Windows here.

File: src/main.rs [hunk 3]
```diff
@@ -74,13 +80,14 @@ fn main() {
...
         // Only update the gain if we know what the last reference was
-        match known {
-            true => known = !update_gain(current_gain, new_gain),
-            false => {
-                known = true;
-                current_gain = new_gain;
-            }
-        };
+        if known {
+            // Invalidate the known gain if we updated it, since it's not certain what miniDSP returns
```
Comment (ElitCoder) [inline src/main.rs:84]: Reading the gain after an update is based on the fact that it's not certain that the miniDSP returns the exact gain that was written... it's kind of a black box, literally.

File: src/main.rs [hunk 4]
```diff
@@ -15,23 +16,28 @@ const SLEEP_TIME_MS: u64 = 50;
 const MINIDSP_GAIN_MIN: f64 = -127.0;
 const MINIDSP_GAIN_MAX: f64 = 0.0;
 
+// Lazy static needed since Regex::new() is a function call
+lazy_static! {
```
Comment (Lundez) [inline src/main.rs:20]: Not sure why we make it lazy. It'll be called, and will be called pretty fast. Usually lazy is used for expensive operations that might not be used? 👍

File: src/main.rs [hunk 5]
```diff
@@ -15,23 +16,28 @@ const SLEEP_TIME_MS: u64 = 50;
...
         .expect("Failed to retrieve current gain");
     let output_string =
         String::from_utf8(output.stdout).expect("Failed to convert output to string");
 
-    // Fetch gain through regex
-    let gain_regex =
-        Regex::new(r"Gain\((?P<gain>-*\d*\.*\d*)\)").expect("Failed to create regex for gain");
-    let capture_groups = gain_regex
+    // Capture gain through regex
+    let capture_groups = GAIN_REGEX
```
Comment (Lundez) [inline src/main.rs]: Better naming? What do you capture? 😍

File: src/main.rs (hunk 2 above)
Comment (Lundez) [reply src/main.rs:43]: Sick moves. This is why low-level confuses me ❤️
Logger is std in jvm

File: src/main.rs (hunk 3 above)
Comment (Lundez) [reply src/main.rs:84]: Lawl. RIP

**Review by Lundez — APPROVED** [review]
LGTM low-level code sucks ❤️🥳

File: src/main.rs (hunk 4 above)
Comment (ElitCoder) [reply src/main.rs:20]: Normal "static" doesn't work since Rust won't accept it. Probably due to the size needs to be known at compile time.

I agree that lazy is a bit weird here, any suggestions that still avoids initializing the regex on each call?

File: src/main.rs (hunk 5 above)
Comment (ElitCoder) [reply src/main.rs]: Somewhat done? :smiley:

File: src/main.rs (hunk 4 above)
Comment (Lundez) [reply src/main.rs:20]: Uhm how about a `const`? Shouldn't that be possible?

**Comment by Lundez** [comment]
It's funny how you added CI for something that has no tests btw <3

LGTM 🌟 
(though I think the regexp can be `const` or something else it's just BS optimizations hahah)

File: Cargo.toml [hunk 6]
```diff
@@ -5,5 +5,6 @@ authors = ["Niklas Carlsson <niklas.carlsson1994@gmail.com>"]
 edition = "2018"
 
 [dependencies]
+lazy_static = "1.4.0"
```
Comment (Lundez) [inline Cargo.toml:8]: Mother of God, it's a dependency?

File: src/main.rs (hunk 4 above)
Comment (ElitCoder) [reply src/main.rs:20]: const is just search and replace in Rust, the compiler won't accept it... this regex is tearing me apart.

File: Cargo.toml (hunk 6 above)
Comment (ElitCoder) [reply Cargo.toml:8]: Of course it is :smiley: this is Rust!

**Comment by ElitCoder** [comment]
> It's funny how you added CI for something that has no tests btw <3
> 
> LGTM 
> (though I think the regexp can be `const` or something else it's just BS optimizations hahah)

Really can't figure out anything else about the regex and I frankly don't care since this is as performant as it can be I guess :stuck_out_tongue:

Let's pretend the CI is just checking that everything builds :+1:
